### PR TITLE
Allow Deep to build from a subdirectory

### PR DESCRIPTION
**Pull request by mrgordon**

### CODE REVIEW

**Comment by beedub** [comment]
still need to figure out the paths on this one

**Comment by mrgordon** [comment]
Yeah needed to merge to test anyway. I see it doesn't work yet :)

**Comment by beedub** [comment]
you can test without merging actually. heroku buildpacks support specific branches by appending `#<branch>` to the buildpack url (https://devcenter.heroku.com/articles/buildpacks)

**Comment by mrgordon** [comment]
Nice! Thanks for the tip

**Comment by beedub** [comment]
(am working on this now btw)

**Pull request merged**
